---
driver:
  name: dokken
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  chef_license: accept-no-persist
  privileged: true
  tmpfs:
    /var/lib/docker: rw

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: debian-10
  driver:
    image: dokken/debian-10
    pid_one_command: /bin/systemd

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-30
  driver:
    image: dokken/fedora-30
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd

suites:
  - name: package_1_17
    run_list:
      - recipe[kubelet_test::installation_package]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/package
    attributes:
      kubelet_test:
        version: '1.17.0'

  - name: package_1_16
    run_list:
      - recipe[kubelet_test::installation_package]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/package
    attributes:
      kubelet_test:
        version: '1.16.4'

  - name: package_1_15
    run_list:
      - recipe[kubelet_test::installation_package]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/package
    attributes:
      kubelet_test:
        version: '1.15.7'

  - name: binary_1_17
    run_list:
      - recipe[kubelet_test::installation_binary]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/binary
    attributes:
      kubelet_test:
        version: '1.17.0'
        checksum: 'c2af77f501c3164e80171903028d35c632366f53dec0c8419828d4e55d86146f'
        kubelet_bin: '/opt/bin/kubelet'

  - name: binary_1_16
    run_list:
      - recipe[kubelet_test::installation_binary]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/binary
    attributes:
      kubelet_test:
        version: '1.16.4'
        checksum: 'a2f1eec9ecccebceb5032322ebc5e8cc054220c41cd4ec7b7b460cb8bfd63481'
        kubelet_bin: '/opt/bin/kubelet'

  - name: binary_1_15
    run_list:
      - recipe[kubelet_test::installation_binary]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/binary
    attributes:
      kubelet_test:
        version: '1.15.7'
        checksum: 'e018fc3b934cb5325bc55444e029ddc357544191132794162de9e3663dd7e952'
        kubelet_bin: '/opt/bin/kubelet'
