---
driver:
  name: dokken
  chef_version: latest
  privileged: true
  tmpfs:
    /var/lib/docker: rw

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-28
  driver:
    image: dokken/fedora-28
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-18.04
  driver:
    image: dokken/ubuntu-18.04
    pid_one_command: /bin/systemd

suites:
  - name: package_1_11
    run_list:
      - recipe[kubelet_test::installation_package]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/package
    attributes:
      kubelet_test:
        version: '1.11.3'

  - name: package_1_10
    run_list:
      - recipe[kubelet_test::installation_package]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/package
    attributes:
      kubelet_test:
        version: '1.10.7'

  - name: binary_1_11
    run_list:
      - recipe[kubelet_test::installation_binary]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/binary
    attributes:
      kubelet_test:
        version: '1.11.3'
        checksum: '7d0767b6efdc565075f0ba219653e8f6b037643ddee946e0d88cccb6714e8f8f'
        kubelet_bin: '/opt/bin/kubelet'

  - name: binary_1_10
    run_list:
      - recipe[kubelet_test::installation_binary]
      - recipe[kubelet_test::service]
    verifier:
      inspec_tests:
        - test/integration/binary
    attributes:
      kubelet_test:
        version: '1.10.7'
        checksum: '530ddd24f86dc129f0658e75c3ea4f70b6fec28bf2126c0b810f87790456e963'
        kubelet_bin: '/opt/bin/kubelet'
