sudo: required

addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=package-1-17-debian-9
  - INSTANCE=package-1-17-centos-7
  - INSTANCE=package-1-17-fedora-28
  - INSTANCE=package-1-17-ubuntu-1804
  - INSTANCE=package-1-16-debian-9
  - INSTANCE=package-1-16-centos-7
  - INSTANCE=package-1-16-fedora-28
  - INSTANCE=package-1-16-ubuntu-1804
  - INSTANCE=package-1-15-debian-9
  - INSTANCE=package-1-15-centos-7
  - INSTANCE=package-1-15-fedora-28
  - INSTANCE=package-1-15-ubuntu-1804
  - INSTANCE=binary-1-17-debian-9
  - INSTANCE=binary-1-17-centos-7
  - INSTANCE=binary-1-17-fedora-28
  - INSTANCE=binary-1-17-ubuntu-1804
  - INSTANCE=binary-1-16-debian-9
  - INSTANCE=binary-1-16-centos-7
  - INSTANCE=binary-1-16-fedora-28
  - INSTANCE=binary-1-16-ubuntu-1804
  - INSTANCE=binary-1-15-debian-9
  - INSTANCE=binary-1-15-centos-7
  - INSTANCE=binary-1-15-fedora-28
  - INSTANCE=binary-1-15-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
